//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreAPI.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class livro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public livro()
        {
            this.autor = new HashSet<autor>();
        }
    
        public int ID_LIVRO { get; set; }
        public string TITULO_LIVRO { get; set; }
        public float PRECO_LIVRO { get; set; }
        public int ID_EDITORA_LIVRO { get; set; }
        public int ID_ASSUNTO_LIVRO { get; set; }
    
        public virtual assunto assunto { get; set; }
        public virtual editora editora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<autor> autor { get; set; }
    }
}
