//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreAPI.BookStoreModels.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int ID_USUARIO { get; set; }
        public string NOME_USUARIO { get; set; }
        public string SOBRENOME_USUARIO { get; set; }
        public string LOGIN_USUARIO { get; set; }
        public string SENHA_USUARIO { get; set; }
    }
}
